#!/usr/bin/env bash
# Deploys the test namespaces, NetworkAttachmentDefinitions, and
# client/server pods, waits for them to be Ready, discovers their
# dynamically assigned secondary IPs, and writes them to results/topology.env
# for use by all other test scripts.
set -euo pipefail
source "$(dirname "$0")/lib.sh"

log "Applying namespaces, NetworkAttachmentDefinitions, and workloads"
kubectl apply -f "${ROOT_DIR}/00-namespaces.yaml"
kubectl apply -f "${ROOT_DIR}/01-network-attachments.yaml"
kubectl apply -f "${ROOT_DIR}/02-workloads.yaml"

log "Waiting for pods to become Ready"
kubectl wait --for=condition=Ready pod --all -n mnp-test-a --timeout=180s
kubectl wait --for=condition=Ready pod --all -n mnp-test-b --timeout=180s

log "Discovering secondary IPs (may take a few seconds after Ready)"
sleep 3

SERVER_IP_A="$(get_net_ip mnp-test-a server test-net-a)"
SERVER_IP_B="$(get_net_ip mnp-test-a server test-net-b)"
CLIENT_IP_A="$(get_net_ip mnp-test-a client test-net-a)"
CLIENT_IP_B="$(get_net_ip mnp-test-a client test-net-b)"
CLIENT_B_IP_A="$(get_net_ip mnp-test-a client-b test-net-a)"
CLIENT_OTHERNS_IP_A="$(get_net_ip mnp-test-b client-other-ns test-net-a)"

for var in SERVER_IP_A SERVER_IP_B CLIENT_IP_A CLIENT_IP_B CLIENT_B_IP_A CLIENT_OTHERNS_IP_A; do
  if [[ -z "${!var}" ]]; then
    echo "ERROR: failed to discover ${var}. Check 'kubectl describe pod' and multus/whereabouts logs." >&2
    exit 1
  fi
done

cat > "${TOPOLOGY_ENV}" <<EOF
# Generated by 10-deploy-topology.sh - do not edit by hand.
SERVER_IP_A=${SERVER_IP_A}
SERVER_IP_B=${SERVER_IP_B}
CLIENT_IP_A=${CLIENT_IP_A}
CLIENT_IP_B=${CLIENT_IP_B}
CLIENT_B_IP_A=${CLIENT_B_IP_A}
CLIENT_OTHERNS_IP_A=${CLIENT_OTHERNS_IP_A}
TESTNET_A_CIDR=192.168.101.0/24
TESTNET_B_CIDR=192.168.102.0/24
EOF

log "Topology ready"
column -t -s= "${TOPOLOGY_ENV}" | grep -v '^#'

echo
echo "Topology deployed. IPs saved to ${TOPOLOGY_ENV}"
