apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: network-multitool
  name: network-multitool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: network-multitool
  template:
    metadata:
      labels:
        app: network-multitool
    spec:
      containers:
      - name: network-multitool
        image: wbitt/network-multitool:extra
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
