# Image URIs for sriov-network-operator components
images:
  operator:
    repository: rancher/hardened-sriov-network-operator
    tag: v1.2.0-build20230912
  sriovConfigDaemon:
    repository: rancher/hardened-sriov-network-config-daemon
    tag: v1.2.0-build20230912
  sriovCni:
    repository: rancher/hardened-sriov-cni
    tag: v2.6.3-build20230913
  ibSriovCni: 
    repository: rancher/hardened-ib-sriov-cni
    tag: v1.0.2-build20230911
  sriovDevicePlugin: 
    repository: rancher/hardened-sriov-network-device-plugin
    tag: v3.5.1-build20230911
  resourcesInjector: 
    repository: rancher/hardened-sriov-network-resources-injector
    tag: v1.5-build20230911
  webhook:
    repository: rancher/hardened-sriov-network-webhook
    tag: v1.2.0-build20230912
