apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: example-network
  namespace: kube-system
spec:
  ipam: |
    {
      "type": "whereabouts",
      "range": "192.168.2.0/24"
    }
  vlan: 0 
  resourceName: sriovmako
